FROM ubuntu:18.04
MAINTAINER dhk1349 "dhk1349@gmail.com"
RUN apt-get update -y
RUN apt-get -y upgrade
RUN apt-get install -y python-pip python-dev build-essential
RUN mv bedtools.static.binary bedtools

